---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# bdformats

In raster:

```{r}
library(raster)
region = sf::as_Spatial(spData::lnd)
raster(region)
r = raster::raster(spData::lnd, ncols = 3, nrows = 3)
raster::values(r) = runif(9)
raster::plot(r)
r2 = raster(r)
values(r2) = runif(9)
# b = brick(system.file("external/rlogo.grd", package="raster"))
b = brick(r, r2)
plot(b)
m = mapview::mapview(b)
m@map
```

In mapdeck:

```{r}
df = data.frame(
  lng = runif(1000, 0, 1),
  lat = runif(1000, 52, 53)
  )
library(mapdeck)
ms = mapdeck_style("dark")
mapdeck(style = ms, pitch = 45, location = c(0, 52), zoom = 4) %>%
add_grid(data = df, lat = "lat", lon = "lng", cell_size = 10000,
         elevation_scale = 50, layer_id = "grid_layer",
         colour_range = viridisLite::plasma(6))
```

# NetCDF data

Get data:

```{r, eval=FALSE, echo=FALSE}
piggyback::pb_upload("Example_Met_Office_H5_Data_Share-20210614T102649Z-002.zip")
```

```{r, eval=FALSE}
if(!file.exists("Example_Met_Office_H5_Data_Share-20210614T102649Z-002.zip")) {
  download.file("...")
}

if(!dir.exists("Example_Met_Office_H5_Data_Share")) {
  unzip("Example_Met_Office_H5_Data_Share-20210614T102649Z-002.zip")
  unzip("Example_Met_Office_H5_Data_Share/All_Files.zip")
}

```

```{r}
scan1 = stars::read_ncdf("202007170002_polar_pl_radar20b2_augzdr_lp.h5")
```







